### ISSUE TITLE
The citation file is missing

### ISSUE THREAD

**Issue by liekelotte** [carpentries-incubator/lesson-R-packaging#111]
It would be great to have a [citation file](https://citation-file-format.github.io/). This way, any interested user can easily cite our materials.

**Comment by PabRod** [comment]
Hi @liekelotte. Can you please remind me which was the website for starting a new citation file from scratch?

**Comment by liekelotte** [comment]
Hey @PabRod, new citation files can be generated with [cffinit](https://citation-file-format.github.io/cff-initializer-javascript/#/) - let me know if you need any help!
