### ISSUE TITLE
Number the episodes

### ISSUE THREAD

**Issue by multimeric** [carpentries-incubator/lesson-R-packaging#126]
As implied by `?sandpaper::create_episode`, episodes should be numbered. e.g. `08_data.rmd` rather than `data.rmd`.

**Comment by PabRod** [comment]
Not necessarily. The episode order can be controlled via [`config.yaml`](https://github.com/carpentries-incubator/lesson-R-packaging/blob/e65e869ebf46c1268c3464b8785c250e18358cae/config.yaml#L60C1-L71C16).

Keep in mind that using episode numbers becomes a quite annoying problem when you have to add a new episode in between other two.

**Comment by multimeric** [comment]
Indeed, I've come around on this. I also asked on the Carpentries Slack and there was no consensus that it's a good practice.
