### ISSUE TITLE
modular code and refactoring

### ISSUE THREAD

**Issue by bvreede** [carpentries-incubator/lesson-R-packaging#74]
An R package consists of functions. This is introduced in [Episode 4](https://carpentries-incubator.github.io/lesson-R-packaging/04-functions/index.html), but the fact that modular code is essential for packages is not mentioned explicitly. Introducing modules/building blocks and their value in code reuse would be a good addition to this chapter. 

In addition, R users making the step towards packaging may often have to refactor their scripted code to functions, so it is important to understand how to go about this process.

In this chapter, the difference between functions available to the user, and helper functions can also be discussed.

**Comment by PabRod** [comment]
Related to #78
