### ISSUE TITLE
Consider covering test coverage when talking about tests

### ISSUE THREAD

**Issue by n400peanuts** [carpentries-incubator/lesson-R-packaging#84]
Note: this is a suggestion! and sorry about the ugly title!

I found it easy to set up a test coverage on github once I got all my tests in place (and of course a nice metric to evaluate my package) -- perhaps is something worth talking about? 

This is what I set up for my package: https://about.codecov.io/

**Comment by PabRod** [comment]
We'd like to avoid depending on GitHub (for the reasons mentioned [here](https://github.com/carpentries-incubator/lesson-R-packaging/issues/83#issuecomment-1313780108)).

Is it possible to use codecov locally?

**Comment by n400peanuts** [comment]
@PabRod it's possible via the covr package (https://cloud.r-project.org/web/packages/covr/index.html)

**Comment by PabRod** [comment]
Then I agree this is definitely worth mentioning. Thanks a lot for the suggestion!

Are you interested in writing a subsection about it inside [the testing episode](https://carpentries-incubator.github.io/lesson-R-packaging/06-testing/index.html)?

**Comment by n400peanuts** [comment]
sure! I am happy to contribute
